Fix a bug: example/camera_display.py (line 44) gave a numpy array instead an astropy Quantity to ctapipe.reco.hillas_parameters() causing an exception ("AttributeError: 'numpy.ndarray' object has no attribute 'unit'").